# Generated by Django 5.0.4 on 2026-08-30 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['username'], name='idx_profile_username'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user_score'], name='idx_profile_score'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['updated_time'], name='idx_profile_updated'),
        ),
    ]
