# Generated by Django 5.0.4 on 2024-05-11 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='SoldModel',
        ),
        migrations.AlterModelOptions(
            name='soldmodel',
            options={'verbose_name': '商品销量', 'verbose_name_plural': '商品销量'},
        ),
    ]
