# Generated by Django 5.0.4 on 2026-04-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soldmodel',
            options={'verbose_name': '综合数据看板', 'verbose_name_plural': '综合数据看板'},
        ),
    ]
