# Generated by Django 5.0.4 on 2024-05-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_initial'),
        ('customer', '0003_remove_orderinfos_address_remove_orderinfos_user_and_more'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='ShoppingCart',
        ),
    ]
