# Generated by Django 5.0.4 on 2024-05-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_alter_orderinfos_user_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='goods_num',
            field=models.IntegerField(default=1, verbose_name='商品数量'),
        ),
    ]
