# Generated by Django 5.0.4 on 2026-08-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_orderinfos_confirmed_time_ordergoods_commented'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordergoods',
            options={'ordering': ['-add_time', '-id'], 'verbose_name': '订单商品', 'verbose_name_plural': '订单商品'},
        ),
        migrations.AlterModelOptions(
            name='orderinfos',
            options={'ordering': ['-created_time', '-id'], 'verbose_name': '订单信息', 'verbose_name_plural': '订单信息'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ['-created_time', '-id'], 'verbose_name': '购物车', 'verbose_name_plural': '购物车'},
        ),
    ]
