# Generated by Django 5.0.4 on 2026-08-30 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0004_alter_commodityinfos_detail_images_and_more'),
        ('customer_operation', '0008_useraddress_idx_address_user_and_more'),
        ('trade', '0006_alter_ordergoods_options_alter_orderinfos_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderinfos',
            index=models.Index(fields=['user'], name='idx_order_user'),
        ),
        migrations.AddIndex(
            model_name='orderinfos',
            index=models.Index(fields=['order_sn'], name='idx_order_sn'),
        ),
        migrations.AddIndex(
            model_name='orderinfos',
            index=models.Index(fields=['order_status'], name='idx_order_status'),
        ),
        migrations.AddIndex(
            model_name='orderinfos',
            index=models.Index(fields=['created_time'], name='idx_order_created'),
        ),
        migrations.AddIndex(
            model_name='orderinfos',
            index=models.Index(fields=['refund_status'], name='idx_order_refund'),
        ),
        migrations.AddIndex(
            model_name='orderinfos',
            index=models.Index(fields=['user', 'order_status', 'created_time'], name='idx_order_user_list'),
        ),
        migrations.AddIndex(
            model_name='shoppingcart',
            index=models.Index(fields=['user'], name='idx_cart_user'),
        ),
        migrations.AddIndex(
            model_name='shoppingcart',
            index=models.Index(fields=['commodity'], name='idx_cart_commodity'),
        ),
        migrations.AddIndex(
            model_name='shoppingcart',
            index=models.Index(fields=['user', 'commodity'], name='idx_cart_user_commodity'),
        ),
    ]
