# Generated by Django 5.1.15 on 2026-08-30 11:03

import django.db.models.deletion
from django.db import migrations, models


def clean_orphan_cart_commodities(apps, schema_editor):
	"""
	db_constraint=False 时代留下的脏数据：commodity_id 指向已不存在的
	商品。加 FK 约束前必须清掉，否则 ALTER TABLE 会失败。
	"""
	ShoppingCart = apps.get_model('trade', 'ShoppingCart')
	CommodityInfos = apps.get_model('commodity', 'CommodityInfos')
	valid_ids = CommodityInfos.objects.values_list('id', flat=True)
	ShoppingCart.objects.exclude(commodity_id=None).exclude(
		commodity_id__in=valid_ids
	).update(commodity_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0004_alter_commodityinfos_detail_images_and_more'),
        ('trade', '0007_orderinfos_idx_order_user_orderinfos_idx_order_sn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commodity.commodityinfos', verbose_name='商品'),
        ),
        migrations.RunPython(clean_orphan_cart_commodities, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='shoppingcart',
            name='commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commodity.commodityinfos', verbose_name='商品'),
        ),
    ]
