# Generated by Django 5.0.4 on 2024-05-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavingmessage',
            name='file',
            field=models.FileField(blank=True, help_text='上传的文件', null=True, upload_to='leaving_message_imgs/', verbose_name='上传的文件'),
        ),
    ]
