# Generated by Django 5.0.4 on 2024-05-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_operation', '0002_alter_userleavingmessage_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='province',
            field=models.CharField(default='', max_length=100, verbose_name='省/直辖市'),
        ),
    ]
