# Generated by Django 5.0.4 on 2024-05-11 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_operation', '0003_usercomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='updated_time',
        ),
    ]
