# Generated by Django 5.0.4 on 2024-05-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_operation', '0004_remove_usercomment_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleavingmessage',
            name='is_replied',
            field=models.BooleanField(default=False, verbose_name='是否已回复'),
        ),
        migrations.AddField(
            model_name='userleavingmessage',
            name='reply_content',
            field=models.TextField(blank=True, default='', help_text='回复内容', null=True, verbose_name='回复内容'),
        ),
        migrations.AddField(
            model_name='userleavingmessage',
            name='reply_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='回复时间'),
        ),
        migrations.AlterField(
            model_name='userleavingmessage',
            name='file',
            field=models.ImageField(blank=True, help_text='上传的图片件', null=True, upload_to='leaving_message_imgs/', verbose_name='上传的图片'),
        ),
    ]
