# Generated by Django 5.0.4 on 2026-08-25 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_operation', '0005_userleavingmessage_is_replied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='rating',
            field=models.IntegerField(default=5, help_text='评分范围从1到5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评分'),
        ),
    ]
