# Generated by Django 5.0.4 on 2026-08-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_operation', '0006_alter_usercomment_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ['-is_default', '-created_time', '-id'], 'verbose_name': '收货地址', 'verbose_name_plural': '收货地址'},
        ),
        migrations.AlterModelOptions(
            name='usercomment',
            options={'ordering': ['-created_time', '-id'], 'verbose_name': '用户评论', 'verbose_name_plural': '用户评论'},
        ),
        migrations.AlterModelOptions(
            name='userfav',
            options={'ordering': ['-add_time', '-id'], 'verbose_name': '用户收藏', 'verbose_name_plural': '用户收藏'},
        ),
        migrations.AlterModelOptions(
            name='userleavingmessage',
            options={'ordering': ['-add_time', '-id'], 'verbose_name': '用户留言', 'verbose_name_plural': '用户留言'},
        ),
    ]
