# Generated by Django 5.0.4 on 2026-08-30 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0004_alter_commodityinfos_detail_images_and_more'),
        ('customer_operation', '0007_alter_useraddress_options_alter_usercomment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user'], name='idx_address_user'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['is_default'], name='idx_address_default'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'is_default'], name='idx_address_user_default'),
        ),
        migrations.AddIndex(
            model_name='usercomment',
            index=models.Index(fields=['user'], name='idx_comment_user'),
        ),
        migrations.AddIndex(
            model_name='usercomment',
            index=models.Index(fields=['commodity'], name='idx_comment_commodity'),
        ),
        migrations.AddIndex(
            model_name='usercomment',
            index=models.Index(fields=['rating'], name='idx_comment_rating'),
        ),
        migrations.AddIndex(
            model_name='usercomment',
            index=models.Index(fields=['is_show'], name='idx_comment_show'),
        ),
        migrations.AddIndex(
            model_name='usercomment',
            index=models.Index(fields=['created_time'], name='idx_comment_time'),
        ),
        migrations.AddIndex(
            model_name='usercomment',
            index=models.Index(fields=['commodity', 'is_show', 'created_time'], name='idx_comment_product_list'),
        ),
        migrations.AddIndex(
            model_name='userfav',
            index=models.Index(fields=['user'], name='idx_fav_user'),
        ),
        migrations.AddIndex(
            model_name='userfav',
            index=models.Index(fields=['goods'], name='idx_fav_goods'),
        ),
        migrations.AddIndex(
            model_name='userfav',
            index=models.Index(fields=['add_time'], name='idx_fav_time'),
        ),
        migrations.AddIndex(
            model_name='userleavingmessage',
            index=models.Index(fields=['user'], name='idx_message_user'),
        ),
        migrations.AddIndex(
            model_name='userleavingmessage',
            index=models.Index(fields=['message_type'], name='idx_message_type'),
        ),
        migrations.AddIndex(
            model_name='userleavingmessage',
            index=models.Index(fields=['is_replied'], name='idx_message_replied'),
        ),
        migrations.AddIndex(
            model_name='userleavingmessage',
            index=models.Index(fields=['add_time'], name='idx_message_time'),
        ),
    ]
