# Generated by Django 5.0.4 on 2026-08-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-created_time', '-id'], 'verbose_name': '广告信息', 'verbose_name_plural': '广告信息'},
        ),
    ]
