# Generated by Django 5.0.4 on 2024-05-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_by',
            field=models.CharField(max_length=255, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='updated_by',
            field=models.CharField(max_length=255, null=True, verbose_name='创建人'),
        ),
    ]
