# Generated by Django 5.0.4 on 2024-05-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='更新人'),
        ),
    ]
