# Generated by Django 5.0.4 on 2024-05-06 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_alter_admin_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
    ]
