# Generated by Django 5.0.4 on 2024-05-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0003_remove_admin_last_login_remove_admin_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Administrator',
        ),
    ]
