# Generated by Django 5.0.4 on 2024-05-06 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_rename_admin_administrator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
