# Generated by Django 5.0.4 on 2024-04-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfos',
            name='email',
            field=models.EmailField(default='123@qq.com', max_length=254, verbose_name='邮箱'),
            preserve_default=False,
        ),
    ]
