# Generated by Django 5.0.4 on 2024-04-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_address_admin_advertisement_cart_item_orderinfo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_pass',
            new_name='password',
        ),
    ]
