# Generated by Django 5.0.4 on 2024-04-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_user_pass_userinfo_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间'),
        ),
    ]
