# Generated by Django 5.0.4 on 2024-05-06 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_title', models.CharField(max_length=255, verbose_name='商品名称')),
                ('sku_description', models.CharField(blank=True, max_length=255, verbose_name='商品描述')),
                ('main_image', models.ImageField(upload_to='product_photos/', verbose_name='商品主图')),
                ('detail_images', models.CharField(blank=True, max_length=255, verbose_name='商品细节图')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=6, max_digits=24, verbose_name='商品进价')),
                ('price', models.DecimalField(decimal_places=6, max_digits=24, verbose_name='商品售价')),
                ('status', models.CharField(default='1', max_length=32, verbose_name='商品状态')),
                ('stock_quantity', models.PositiveIntegerField(blank=True, verbose_name='库存数量')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='CommodityCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='类型')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='commodity.commoditycategories', verbose_name='父级类型')),
            ],
            options={
                'verbose_name': '商品类型',
                'verbose_name_plural': '商品类型',
            },
        ),
    ]
