# Generated by Django 5.0.4 on 2024-05-07 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodity', '0001_initial'),
        ('customer', '0001_initial'),
        ('customer_operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityinfos',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commodities', to='customer.userinfos', verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='commodityinfos',
            name='likes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_operation.userfav', verbose_name='收藏数量'),
        ),
        migrations.AddField(
            model_name='commodityinfos',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.commoditycategories', verbose_name='商品类型'),
        ),
        migrations.AddField(
            model_name='commodityinfos',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_commodities', to='customer.userinfos', verbose_name='更新人'),
        ),
    ]
