# Generated by Django 5.0.4 on 2024-05-06 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodity', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityinfos',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commodities', to='customer.userinfos', verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='commodityinfos',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_commodities', to='customer.userinfos', verbose_name='更新人'),
        ),
    ]
