# Generated by Django 5.0.4 on 2024-05-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityinfos',
            name='detail_images',
            field=models.ImageField(upload_to='product_photos_details/', verbose_name='商品主图'),
        ),
    ]
