# Generated by Django 5.0.4 on 2026-08-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_alter_commodityinfos_cost_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodityinfos',
            options={'ordering': ['-created_time', '-id'], 'verbose_name': '商品信息', 'verbose_name_plural': '商品信息'},
        ),
    ]
