# Generated by Django 5.0.4 on 2026-08-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_alter_commodityinfos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityinfos',
            name='detail_images',
            field=models.ImageField(upload_to='product_photos_details/', verbose_name='商品详情图'),
        ),
        migrations.AddIndex(
            model_name='commodityinfos',
            index=models.Index(fields=['sku_title'], name='idx_commodity_title'),
        ),
        migrations.AddIndex(
            model_name='commodityinfos',
            index=models.Index(fields=['status'], name='idx_commodity_status'),
        ),
        migrations.AddIndex(
            model_name='commodityinfos',
            index=models.Index(fields=['types'], name='idx_commodity_types'),
        ),
        migrations.AddIndex(
            model_name='commodityinfos',
            index=models.Index(fields=['price'], name='idx_commodity_price'),
        ),
        migrations.AddIndex(
            model_name='commodityinfos',
            index=models.Index(fields=['created_time'], name='idx_commodity_created'),
        ),
        migrations.AddIndex(
            model_name='commodityinfos',
            index=models.Index(fields=['sold'], name='idx_commodity_sold'),
        ),
        migrations.AddIndex(
            model_name='commodityinfos',
            index=models.Index(fields=['status', 'types', 'created_time'], name='idx_commodity_list'),
        ),
    ]
