# Generated by Django 5.0.4 on 2024-05-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_alter_commodityinfos_detail_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityinfos',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='收藏数量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commodityinfos',
            name='sold',
            field=models.IntegerField(default=0, verbose_name='已售数量'),
            preserve_default=False,
        ),
    ]
