# Generated by Django 5.0.4 on 2024-05-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_alter_commodityinfos_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodityinfos',
            name='likes',
        ),
    ]
