# Generated by Django 5.0.4 on 2024-05-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0004_remove_commodityinfos_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityinfos',
            name='sold',
            field=models.IntegerField(default=0, verbose_name='已售数量'),
        ),
    ]
