# Generated by Django 5.0.4 on 2024-05-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0004_commodityinfos_likes_commodityinfos_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityinfos',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=24, verbose_name='商品售价'),
        ),
    ]
