# Generated by Django 5.0.4 on 2024-05-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0005_alter_commodityinfos_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityinfos',
            name='updated_by',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='更新人'),
        ),
    ]
