# Generated by Django 5.0.4 on 2024-05-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0005_alter_commodityinfos_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityinfos',
            name='types',
            field=models.CharField(default=1, max_length=100, verbose_name='商品类型'),
            preserve_default=False,
        ),
    ]
