# Generated by Django 5.0.4 on 2026-08-29 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='分片内容')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='片序')),
                ('embedding_model', models.CharField(blank=True, default='', max_length=100, verbose_name='向量模型')),
                ('embedding_json', models.TextField(blank=True, default='', verbose_name='向量')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '知识库分片',
                'verbose_name_plural': '知识库分片',
                'ordering': ['document_id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文档标题')),
                ('category', models.CharField(blank=True, default='', max_length=50, verbose_name='分类')),
                ('source_file', models.FileField(blank=True, help_text='支持 .txt / .md。上传后需要执行「重新索引」才会生效。', null=True, upload_to='knowledge/', verbose_name='源文件')),
                ('raw_text', models.TextField(blank=True, default='', help_text='可直接粘贴内容；留空则读取上传的源文件。', verbose_name='文本内容')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('indexing', '索引中'), ('ready', '已就绪'), ('failed', '索引失败')], default='pending', max_length=16, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('chunk_count', models.PositiveIntegerField(default=0, verbose_name='分片数')),
                ('is_active', models.BooleanField(default=True, help_text='停用后该文档不再参与 AI 检索，但分片会保留。', verbose_name='启用')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '知识库文档',
                'verbose_name_plural': '知识库文档',
                'ordering': ['-updated_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsultSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='会话标题')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consult_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI 会话',
                'verbose_name_plural': 'AI 会话',
                'ordering': ['-updated_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsultMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '顾问')], max_length=16, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='index.consultsession', verbose_name='所属会话')),
                ('cited_chunks', models.ManyToManyField(blank=True, related_name='citations', to='index.knowledgechunk', verbose_name='引用分片')),
            ],
            options={
                'verbose_name': 'AI 消息',
                'verbose_name_plural': 'AI 消息',
                'ordering': ['session_id', 'created_time', 'id'],
            },
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='index.knowledgedocument', verbose_name='所属文档'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['document', 'position'], name='index_knowl_documen_a955b8_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['embedding_model'], name='index_knowl_embeddi_598715_idx'),
        ),
    ]
