"""
Django's settings for pet_shop project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
import ipaddress
import platform
from pathlib import Path
from datetime import timedelta

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# 加载环境变量
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
def _env_bool(name: str, default: bool) -> bool:
	raw = os.environ.get(name)
	if raw is None:
		return default
	return raw.strip().lower() in {'1', 'true', 'yes', 'on'}


def _env_list(name: str, default: str) -> list[str]:
	return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', True)

# SECURITY WARNING: keep the secret key used in production secret!
# Provide it via DJANGO_SECRET_KEY (see .env.template). The insecure fallback
# is only tolerated while DEBUG is on, so local development still works with
# no configuration, but an unconfigured production boot fails loudly.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '').strip()
if not SECRET_KEY:
	if DEBUG:
		SECRET_KEY = 'django-insecure-local-dev-only-never-deploy-this-value'
	else:
		raise ImproperlyConfigured(
			'DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is off. '
			'Generate one with: python -c "from django.core.management.utils '
			'import get_random_secret_key; print(get_random_secret_key())"'
		)

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost')
# AUTH_USER_MODEL = 'accounts.UserProfile'

# Application definition

INSTALLED_APPS = [
	'simpleui',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'rest_framework',
	'corsheaders',
	'phonenumber_field',
	'index.apps.IndexConfig',  # 注册index
	'commodity.apps.CommodityConfig',  # 注册commodity
	'accounts.apps.AccountsConfig',  # 注册accounts
	'merchant.apps.MerchantConfig',  # 注册merchant
	'charts.apps.ChartsConfig',  # 注册charts
	'customer_operation.apps.CustomerOperationConfig',  # 注册customer_operation
	'trade.apps.TradeConfig',  # 注册trade
	# 注：后台图表用的是模板里 CDN 引入的 ECharts，不依赖 django_echarts，
	# 该应用与 pyecharts/django-chartjs 已一并移除。
	'drf_yasg',
	'import_export'
]

MIDDLEWARE = [
	'corsheaders.middleware.CorsMiddleware',
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pet_shop.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [BASE_DIR / 'templates']
		,
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'pet_shop.wsgi.application'

def _windows_host_from_resolv() -> str | None:
	"""
	The first nameserver inside /etc/resolv.conf usually points to the Windows
	host when running under WSL2. Use it if it looks like an IPv4 address.
	"""
	try:
		resolv = Path('/etc/resolv.conf')
		if not resolv.exists():
			return None

		for line in resolv.read_text().splitlines():
			line = line.strip()
			if not line or line.startswith('#'):
				continue
			if line.startswith('nameserver'):
				parts = line.split()
				if len(parts) >= 2:
					ip_candidate = parts[1]
					try:
						ipaddress.IPv4Address(ip_candidate)
						return ip_candidate
					except ipaddress.AddressValueError:
						continue
	except (OSError, UnicodeDecodeError):
		return None
	return None


def detect_mysql_host() -> str:
	"""
	Use Windows host mapping automatically when running under WSL2 so the
	backend can connect to the MySQL server running on Windows.
	"""
	custom_host = os.environ.get('MYSQL_HOST')
	if custom_host:
		return custom_host

	release = platform.uname().release.lower()
	if 'microsoft' in release or 'wsl' in release:
		nameserver_host = _windows_host_from_resolv()
		if nameserver_host:
			return nameserver_host
		return 'host.docker.internal'
	return '127.0.0.1'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.mysql',
		'NAME': os.environ.get('MYSQL_DATABASE', 'pet_shop'),
		'USER': os.environ.get('MYSQL_USER', 'root'),
		'PASSWORD': os.environ.get('MYSQL_PASSWORD', ''),
		'HOST': detect_mysql_host(),
		'PORT': int(os.environ.get('MYSQL_PORT', 3306)),
		'OPTIONS': {
			'charset': 'utf8mb4'
		}
	}
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = 'static/'

# 后台自有静态资源（分析看板的 CSS/JS、后台品牌 logo）放在 pet_shop/static/。
# 这个目录必须登记进 STATICFILES_DIRS —— 只配 STATIC_ROOT 是不够的：
# STATIC_ROOT 是 collectstatic 的输出目录，不是查找源。少了这一行，
# admin_analytics/*.css|js 会全部 404，后台首页只剩没有样式的“正在加载”文本。
STATICFILES_DIRS = [
	BASE_DIR / 'pet_shop' / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
	# 配置分页器
	'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
	# 每页的数据量
	'PAGE_SIZE': 6,
	# 用户认证方式：前台走 JWT（Authorization: Bearer <token>），
	# SessionAuthentication 仅保留给 DRF 的可浏览 API 与后台内嵌调用。
	# 注意：这里必须使用标准的 SessionAuthentication —— 早期版本用的
	# CsrfExemptSessionAuthentication 会关掉 CSRF 校验，已随本次修复移除。
	'DEFAULT_AUTHENTICATION_CLASSES': (
		'rest_framework_simplejwt.authentication.JWTAuthentication',
		'rest_framework.authentication.SessionAuthentication',
	),
	# 只放全局的“必须登录”。对象归属校验由各 ViewSet 自己声明
	# （IsOwnerOrReadOnly 依赖 obj.user，放在全局会对没有 user 字段的
	# 模型抛 AttributeError，而且多个同名类 AND 在一起没有意义）。
	'DEFAULT_PERMISSION_CLASSES': [
		'rest_framework.permissions.IsAuthenticated',
	],
	# 限流：保护验证码、登录与 AI 端点这类高成本/可滥用入口
	'DEFAULT_THROTTLE_CLASSES': [
		'rest_framework.throttling.ScopedRateThrottle',
	],
	'DEFAULT_THROTTLE_RATES': {
		'ai_consult': os.environ.get('THROTTLE_AI_CONSULT', '10/min'),
		'captcha': os.environ.get('THROTTLE_CAPTCHA', '30/min'),
		'login': os.environ.get('THROTTLE_LOGIN', '10/min'),
	},
}

SIMPLE_JWT = {
	'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.environ.get('JWT_ACCESS_MINUTES', 60))),
	'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.environ.get('JWT_REFRESH_DAYS', 7))),
	'ROTATE_REFRESH_TOKENS': False,
	'AUTH_HEADER_TYPES': ('Bearer',),
	# 需要它来保持 last_login 的更新 —— 登录不再走 django 的 login()，
	# 而 authenticate() 本身不会写 last_login。
	'UPDATE_LAST_LOGIN': True,
}

# 设置跨域访问
# 不再使用 CORS_ORIGIN_ALLOW_ALL —— 通配符来源与 CORS_ALLOW_CREDENTIALS
# 同时开启会允许任意站点带着用户凭据调用本 API。
CORS_ALLOWED_ORIGINS = _env_list(
	'CORS_ALLOWED_ORIGINS',
	'http://localhost:8010,http://127.0.0.1:8010',
)
# 允许携带凭据，但仅限上面白名单内的来源
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = _env_list(
	'CSRF_TRUSTED_ORIGINS',
	'http://localhost:8010,http://127.0.0.1:8010',
)
# 允许执行的请求方式
CORS_ALLOW_METHODS = (
	'DELETE',
	'GET',
	'OPTIONS',
	'PATCH',
	'POST',
	'PUT',
	'VIEW',
)
# 允许执行的请求头
CORS_ALLOW_HEADERS = (
	'accept',
	'accept-encoding',
	'authorization',
	'content-type',
	'dnt',
	'origin',
	'user-agent',
	'x-csrftoken',
	'x-requested-with',
)
# 将媒体文件的存储位置设置在了项目的根目录下的一个名为 media 的文件夹内
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# 指定了在浏览器中访问这些媒体文件的 URL 前缀
MEDIA_URL = 'media/'

# 商品预览限制（未登录用户）
COMMODITY_PREVIEW_LIMIT = int(os.environ.get('COMMODITY_PREVIEW_LIMIT', 6))

# 隐藏右侧SimpleUI广告链接和使用分析
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False

# 后台 logo 与前台共用同一个文件（pet_shop/static/admin_brand/logo.png 从
# frontstage/pet_shop/public/img/logo.png 复制而来）。
# 注意：SimpleUI 的 logo 只能通过这个 setting 配置。它的 base.html 里没有
# {% block branding %}，所以在 base_site.html 里覆盖 branding 会被静默丢弃。
# STATIC_URL 是 'static/'（无前导斜杠），直接拼接会得到相对地址，在
# /admin/login/ 这类子路径下会解析成 /admin/login/static/... 而 404。
# 这里显式补上前导斜杠，保证是站点根绝对路径。
SIMPLEUI_LOGO = '/' + STATIC_URL.lstrip('/') + 'admin_brand/logo.png'

# 后台首页加载经营概览页。这是 SimpleUI 支持的自定义首页方式：概览会渲染在
# 外壳的第一个标签页里，侧边栏与 logo 保持完整。
# 不要改回覆盖 templates/admin/index.html —— 那个模板就是 SimpleUI 的外壳本身，
# 覆盖它会导致后台登录后布局全部丢失。
SIMPLEUI_HOME_PAGE = '/api/charts/overview/page/'
SIMPLEUI_HOME_TITLE = '经营概览'
SIMPLEUI_HOME_ICON = 'el-icon-data-line'

# 设置缓存
# 注意：LocMemCache 是每进程独立的。验证码用它存储，因此在多进程/多机
# 部署下会出现“验证码无效”——上线前应换成 Redis 或 Memcached，并通过
# CACHE_BACKEND / CACHE_LOCATION 覆盖。
CACHES = {
	'default': {
		'BACKEND': os.environ.get(
			'CACHE_BACKEND',
			'django.core.cache.backends.locmem.LocMemCache',
		),
		'LOCATION': os.environ.get('CACHE_LOCATION', 'unique-snowflake'),
	}
}

# 仅在关闭 DEBUG（即非本地开发）时启用的安全加固项
if not DEBUG:
	SECURE_CONTENT_TYPE_NOSNIFF = True
	SECURE_BROWSER_XSS_FILTER = True
	# 注意：这一项目前不生效。simpleui 的 AppConfig.ready() 会无条件从
	# MIDDLEWARE 里 pop 掉 XFrameOptionsMiddleware（它的后台 UI 依赖
	# iframe），且没有开关可关闭该行为。因此 `manage.py check --deploy`
	# 会报 security.W002，且防点击劫持头需要在反向代理层为非 /admin/
	# 路径补上。保留此设置，以便将来替换后台皮肤后自动生效。
	X_FRAME_OPTIONS = 'DENY'
	SESSION_COOKIE_HTTPONLY = True
	SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', True)
	CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', True)
	SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', False)
	SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', 0))
	if SECURE_HSTS_SECONDS:
		SECURE_HSTS_INCLUDE_SUBDOMAINS = True
		SECURE_HSTS_PRELOAD = True
