"""
Django's settings for pet_shop project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
import ipaddress
import platform
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-utyj1&cv+2&m(^36*4c$07u*r@+11bh!bc)1@ej1bk$^@%au8h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
# AUTH_USER_MODEL = 'accounts.UserProfile'

# Application definition

INSTALLED_APPS = [
	'simpleui',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'rest_framework',
	'corsheaders',
	'phonenumber_field',
	'index.apps.IndexConfig',  # 注册index
	'commodity.apps.CommodityConfig',  # 注册commodity
	'accounts.apps.AccountsConfig',  # 注册accounts
	'merchant.apps.MerchantConfig',  # 注册merchant
	'charts.apps.ChartsConfig',  # 注册charts
	'customer_operation.apps.CustomerOperationConfig',  # 注册customer_operation
	'trade.apps.TradeConfig',  # 注册trade
	'django_echarts',
	'django_echarts.contrib.bootstrap5',
	'drf_yasg',
	'import_export'
]

MIDDLEWARE = [
	'corsheaders.middleware.CorsMiddleware',
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	# 'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pet_shop.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [BASE_DIR / 'templates']
		,
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'pet_shop.wsgi.application'

def _windows_host_from_resolv() -> str | None:
	"""
	The first nameserver inside /etc/resolv.conf usually points to the Windows
	host when running under WSL2. Use it if it looks like an IPv4 address.
	"""
	try:
		resolv = Path('/etc/resolv.conf')
		if not resolv.exists():
			return None

		for line in resolv.read_text().splitlines():
			line = line.strip()
			if not line or line.startswith('#'):
				continue
			if line.startswith('nameserver'):
				parts = line.split()
				if len(parts) >= 2:
					ip_candidate = parts[1]
					try:
						ipaddress.IPv4Address(ip_candidate)
						return ip_candidate
					except ipaddress.AddressValueError:
						continue
	except (OSError, UnicodeDecodeError):
		return None
	return None


def detect_mysql_host() -> str:
	"""
	Use Windows host mapping automatically when running under WSL2 so the
	backend can connect to the MySQL server running on Windows.
	"""
	custom_host = os.environ.get('MYSQL_HOST')
	if custom_host:
		return custom_host

	release = platform.uname().release.lower()
	if 'microsoft' in release or 'wsl' in release:
		nameserver_host = _windows_host_from_resolv()
		if nameserver_host:
			return nameserver_host
		return 'host.docker.internal'
	return '127.0.0.1'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.mysql',
		'NAME': os.environ.get('MYSQL_DATABASE', 'pet_shop'),
		'USER': os.environ.get('MYSQL_USER', 'root'),
		'PASSWORD': os.environ.get('MYSQL_PASSWORD', 'xllzy123'),
		'HOST': detect_mysql_host(),
		'PORT': int(os.environ.get('MYSQL_PORT', 3306)),
		'OPTIONS': {
			'charset': 'utf8mb4'
		}
	}
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
	# 配置分页器
	'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
	# 每页的数据量
	'PAGE_SIZE': 6,
	# 用户认证方式
	'DEFAULT_AUTHENTICATION_CLASSES': (
		'pet_shop.authentication.CsrfExemptSessionAuthentication',
		'rest_framework.authentication.BasicAuthentication',
		'rest_framework_simplejwt.authentication.JWTAuthentication',
	),
	'DEFAULT_PERMISSION_CLASSES': [
		'rest_framework.permissions.IsAuthenticated',
		'trade.permissions.IsOwnerOrReadOnly',
		'customer_operation.permissions.IsOwnerOrReadOnly',
	],
}

# 设置跨域访问
# 指定所有域名(IP)都可以访问，默认为False
CORS_ORIGIN_ALLOW_ALL = True
# 设置允许携带Cookie
CORS_ALLOW_CREDENTIALS = True
# 设置允许访问的域名(IP)
# 如果CORS_ORIGIN_ALLOW_ALL=True则无需设置
CORS_ORIGIN_WHITELIST = [
	"http://localhost:8010",
]

CSRF_TRUSTED_ORIGINS = [
	"http://localhost:8010",  # 我的Vue服务器地址
]
# 允许执行的请求方式
CORS_ALLOW_METHODS = (
	'DELETE',
	'GET',
	'OPTIONS',
	'PATCH',
	'POST',
	'PUT',
	'VIEW',
)
# 允许执行的请求头
CORS_ALLOW_HEADERS = (
	'accept',
	'accept-encoding',
	'authorization',
	'content-type',
	'dnt',
	'origin',
	'user-agent',
	'x-csrftoken',
	'x-requested-with',
)
# 将媒体文件的存储位置设置在了项目的根目录下的一个名为 media 的文件夹内
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# 指定了在浏览器中访问这些媒体文件的 URL 前缀
MEDIA_URL = 'media/'

# 商品预览限制（未登录用户）
COMMODITY_PREVIEW_LIMIT = int(os.environ.get('COMMODITY_PREVIEW_LIMIT', 6))

# 隐藏右侧SimpleUI广告链接和使用分析
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False

# 设置缓存
CACHES = {
	'default': {
		'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
		'LOCATION': 'unique-snowflake',
	}
}
