# Generated by Django 5.0.4 on 2024-05-07 23:29

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=24, verbose_name='总金额')),
                ('coupon_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=24, null=True, verbose_name='优惠金额')),
                ('payable_price', models.DecimalField(decimal_places=2, max_digits=24, verbose_name='应付金额')),
                ('pay_method', models.SmallIntegerField(blank=True, choices=[(1, '微信'), (2, '支付宝'), (3, '银联')], verbose_name='支付方式')),
                ('leave_comment', models.CharField(blank=True, max_length=1000, verbose_name='订单留言备注')),
                ('order_status', models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '发货中'), (3, '已签收'), (4, '退货中'), (5, '已退货')], verbose_name='订单状态')),
                ('created_by', models.CharField(max_length=255, verbose_name='创建人')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_by', models.CharField(blank=True, max_length=255, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
        migrations.CreateModel(
            name='UserInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(help_text='用户昵称', max_length=90, verbose_name='用户昵称')),
                ('user_intro', models.CharField(blank=True, help_text='个性签名', max_length=900, verbose_name='个性签名')),
                ('avatar', models.ImageField(blank=True, help_text='头像图片', upload_to='profile_photos/', verbose_name='头像图片')),
                ('email', models.EmailField(help_text='邮件地址', max_length=254, unique=True, verbose_name='邮件地址')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='手机号', max_length=128, region=None, verbose_name='手机号')),
                ('user_status', models.SmallIntegerField(choices=[(0, '冻结'), (1, '正常')], default=1, verbose_name='用户状态')),
                ('token', models.CharField(blank=True, max_length=255, verbose_name='令牌')),
                ('user_score', models.PositiveIntegerField(blank=True, default=80, null=True, verbose_name='用户打分')),
                ('total_cost_amt', models.DecimalField(blank=True, decimal_places=6, default=0.0, max_digits=24, null=True, verbose_name='累计消费金额')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='购买数量')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('commodityInfos', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commodity.commodityinfos', verbose_name='商品信息')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
    ]
