# Generated by Django 5.0.4 on 2024-05-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfos',
            name='created_by',
            field=models.CharField(max_length=255, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='userinfos',
            name='email',
            field=models.EmailField(help_text='邮件地址', max_length=254, unique=True, verbose_name='邮件地址'),
        ),
    ]
