# Generated by Django 5.0.4 on 2024-05-07 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('customer_operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfos',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_operation.useraddress', verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='orderinfos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customer.userinfos', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.userinfos', verbose_name='用户'),
        ),
    ]
