# Generated by Django 5.0.4 on 2024-05-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfos',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderinfos',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='OrderInfos',
        ),
    ]
