# Generated by Django 5.0.4 on 2024-05-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_userinfos_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfos',
            name='coupon_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=24, null=True, verbose_name='优惠金额'),
        ),
        migrations.AlterField(
            model_name='orderinfos',
            name='payable_price',
            field=models.DecimalField(decimal_places=2, max_digits=24, verbose_name='应付金额'),
        ),
        migrations.AlterField(
            model_name='orderinfos',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=24, verbose_name='总金额'),
        ),
    ]
