# Generated by Django 5.0.4 on 2024-05-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_orderinfos_options_orderinfos_update_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfos',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='orderinfos',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '发货中'), (3, '已签收'), (4, '退货中'), (5, '已退货')], verbose_name='订单状态'),
        ),
    ]
