# Generated by Django 5.0.4 on 2024-05-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_orderinfos_update_time_alter_orderinfos_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderinfos',
            options={'verbose_name': '订单信息', 'verbose_name_plural': '订单信息'},
        ),
    ]
